# Generated by Django 5.0.6 on 2024-06-17 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Ввведите место выполнения привычки",
                        max_length=256,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Введите время выполнения привычки",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие, которое нужно выполнить",
                        max_length=256,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Ежедневно"),
                            (2, "Каждые 2 дня"),
                            (3, "Каждые 3 дня"),
                            (4, "Каждые 4 дня"),
                            (5, "Каждые 5 дней"),
                            (6, "Каждые 6 дней"),
                            (7, "Еженедельно"),
                        ],
                        default=1,
                        help_text="Введите периодичность выполнения привычки для напоминания, 1 раз в каждые сколько дней.",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "bonus",
                    models.CharField(
                        blank=True,
                        help_text="Напишите, какое будет вознаграждение за выполнения Полезной привычки",
                        max_length=256,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "execution_duration",
                    models.PositiveIntegerField(
                        help_text="Сколько потребуется времени на выполнение Полезной привычки (в секундах).",
                        verbose_name="Длительность выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Данные признак указывается только для Полезной привычки, если есть связанная с ней, Приятная привычка",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
