# Generated by Django 5.0.6 on 2024-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_associated_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Ежедневно"),
                    (2, "Каждые 2 дня"),
                    (3, "Каждые 3 дня"),
                    (4, "Каждые 4 дня"),
                    (5, "Каждые 5 дней"),
                    (6, "Каждые 6 дней"),
                    (7, "Еженедельно"),
                ],
                help_text="Введите периодичность выполнения привычки для напоминания, 1 раз в каждые сколько дней.",
                null=True,
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
