# Generated by Django 5.0.6 on 2024-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_duration",
            field=models.PositiveIntegerField(
                blank=True,
                default=120,
                help_text="Сколько потребуется времени на выполнение Полезной привычки (в секундах).",
                null=True,
                verbose_name="Длительность выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Ежедневно"),
                    (2, "Каждые 2 дня"),
                    (3, "Каждые 3 дня"),
                    (4, "Каждые 4 дня"),
                    (5, "Каждые 5 дней"),
                    (6, "Каждые 6 дней"),
                    (7, "Еженедельно"),
                ],
                default=1,
                help_text="Введите периодичность выполнения привычки для напоминания, 1 раз в каждые сколько дней.",
                null=True,
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
