# Generated by Django 5.0.6 on 2024-06-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_habit_send_next_date_habit_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="send_next_date",
            new_name="send_date",
        ),
    ]
